version: "3"

services:
  mycv:
    restart: unless-stopped
    image: "wkeplon/mycv:latest"
    env_file:
      - ./.env.docker
    ports:
      - 9000:9000
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: "mongo:4.4.12"
    volumes:
      - ../mongo-volume:/data/db
    ports:
      - 27017:27017
