version: "3"

services:
  mycv:
    restart: unless-stopped
    build: ./
    env_file:
      - ./.env.docker
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 9000:9000
    depends_on:
      - mongodb
  mycv_2:
    restart: unless-stopped
    build: ./
    env_file:
      - ./.env.docker
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 9001:9000
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: "mongo:4.4.12"
    volumes:
      - ../mongo-volume:/data/db
      - ../mongo-volume/configdb:/data/configdb
    ports:
      - 27017:27017
