version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "8000:9090"
    volumes:
      - ./config:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "8001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  mongoclient:
    image: mongo-express:latest
    container_name: mongoclient
    ports:
      - "8002:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://172.17.0.1:27017/mongodb?gssapiServiceName=mongodb
    restart: unless-stopped
